name: Deploy Azure Function (Python)

 

on:

  push:

    branches: [ "main" ]   # 기본 브랜치 이름에 맞게 수정

  workflow_dispatch:

 

env:

  AZURE_FUNCTIONAPP_NAME: "<앱명>"           # 예: my-func-app-123

  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."        # 루트에 프로젝트가 있으면 "."

  PYTHON_VERSION: "3.11"

 

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

 

      - name: Set up Python

        uses: actions/setup-python@v5

        with:

          python-version: ${{ env.PYTHON_VERSION }}

 

      - name: Install dependencies

        run: |

          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

          python -m pip install --upgrade pip

          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

          popd

 

      - name: Deploy to Azure Functions

        uses: Azure/functions-action@v1

        with:

          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}

          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

          scm-do-build-during-deployment: true

          enable-oryx-build: true
