name: Deploy Azure Function (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: "CrawlerTech"     # ← 실제 Function App 이름으로 교체 (예: CrawlerTech)
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."  # 프로젝트가 리포지토리 루트에 있을 때 "."
  PYTHON_VERSION: "3.11"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 의존성 설치는 Oryx 원격 빌드가 자동 처리 (로컬 pip 단계 넣지 않음)

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
