name: Deploy Azure Functions (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required files exist
        run: |
          ls -la
          test -f app.py || (echo "app.py not found in repo root" && exit 1)
          test -f requirements.txt || (echo "requirements.txt not found in repo root" && exit 1)
          test -f host.json || (echo "host.json not found in repo root" && exit 1)

      - name: Set up Python (match Functions runtime)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Oryx가 서버에서 requirements.txt를 기준으로 설치하므로 venv/zip 불필요

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-tc-crawl-kr001              # ✅ 함수앱 '이름'
          package: '.'                               # 리포지토리 루트 배포
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
